[phases.setup]
nixPkgs = ['maven', 'openjdk17']

[phases.install]
cmds = ['mvn clean compile -DskipTests']

[phases.build]
cmds = ['mvn package -DskipTests']

[phases.start]
cmd = 'java -Dserver.port=$PORT -jar target/emplouyee-0.0.1-SNAPSHOT.jar'
